#
# /resources/config/prod/security.yml
#
# This file contains production (prod) environment security related settings for Silex application.
#
# Note that this file is ment for production (prod) environment database settings. Also note that these configuration
# values are common to all devs. If you want to override these settings in your _own_ environment you can create
# 'local.yml' file and override what ever you want in this environment.
#