#
# /resources/config/cli-dev/database.yml
#
# This file contains database related settings for development environment console application.
#
# Note that these settings are common to all devs. If you want to override these settings in your _own_ environment
# you can create 'local.yml' file and override what ever you want in this environment.
#