#
# /resources/config/common/parameters.yml
#
# This file contains common parameters for Silex application.
#
# Note that these settings are used IF any environment OR local specified settings are not configured. If you want to
# override any of these values use environment specified file which is located in dev, prod or test directory. Note
# that these files are binded to application environment and are stored to VCS so those are 'common' to all devs.
#
# If you just want to override these settings in your _own_ environment you can create 'local.yml' file and override
# what ever you want to. Also note that this 'local.yml' can be created to any of following directories under config:
#   - common
#   - test
#   - dev
#   - prod
#

#
# MonologServiceProvider parameters
#
# http://silex.sensiolabs.org/doc/providers/monolog.html
#
monolog:
  monolog.logfile: %rootDir%/var/logs/app.log

#
# SwaggerServiceProvider parameters
#
# https://github.com/jdesrosiers/silex-swagger-provider#parameters
#
swagger:
  srcDir: %rootDir%vendor/zircote/swagger-php/src
  servicePath: %rootDir%src

pimpledump.output_dir: %rootDir%var
