#
# /resources/config/dev/parameters.yml
#
# This file contains development (dev) environment parameter settings for Silex application.
#
# Note that this file is ment for development (dev) environment database settings. Also note that these configuration
# values are common to all devs. If you want to override these settings in your _own_ environment you can create
# 'local.yml' file and override what ever you want in this environment.
#
debug: true
